Issue 209
chaostoolkit/chaostoolkit-lib pull request #219
Opened 2021-04-07 14:49 UTC by Tam-Lin

Think I finally got everything properly signed off on.  Addresses issues #209 and #212.

2021-08-05 14:29 UTC, Lawouach commented
Thank you for the superb analysis and coverage of trying to understand the intent of the code.

Initially, I had never planned on letting nested structures as secrets/configuration. But because I forgot to actively validate against these, they went through the rabbit hole and now it would foolish to not support them. But this may explain why some of these edge case bugs are found.

I think all issues that were rasied are real issues and I'm happy you've made the effort to work on them.

I know our review is late but would it be possible to rebase your branch before we can merge?

Also, my only concern, before I do the thorough review is backward compatibility. I would not agree to a change that breaks existing, specific behavior. Tests seem to pass so that sounds good but I'll review more deeply in a minute.

2021-08-05 14:42 UTC, ciaranevans requested changes

2021-08-05 14:42 UTC, ciaranevans commented on tests/test_secret.py
> +    pass
Hey @Tam-Lin thanks for the PR! @Lawouach is better suited to checking out the majority of the changes, but could you double check to see if you meant to implement these tests?

If so, could they please be implemented, otherwise, could these test definitions be removed as they current don't exercise any functionality 😄 Thanks!

2021-08-05 15:21 UTC, Lawouach requested changes
I think the changes make sense to me and sound clean and keeping compatibility.

We're likely missing a changelog entry and I agree with @ciaranevans, if some tests remain empty, please remove them or implement them :)

2021-09-01 19:08 UTC, Tam-Lin commented
Closing this pull request, and will submit new pull request based on latest version.

2021-09-01 19:08 UTC, closed without merging