Fix stuck/interrupted experiment
chaostoolkit/chaostoolkit-lib pull request #221
Opened 2021-07-12 14:52 UTC by WixoLeo

This is a fix for the following issue:
https://github.com/chaostoolkit/chaostoolkit/issues/210

TL;DR

While using the safeguards addon, when some safeguard probe fails, sometimes it doesn't stop the experiment and instead continues to run. In some cases it gets completely stuck.

Problem is that the chaostoolkit uses Signals in order to interrupt threads. Sometimes the interrupt exception gets caught by that logger and it just swallows it.
Therefore the experiment continues to run.

2021-07-12 15:16 UTC, Lawouach commented
Great. Could you add a changelog entry (your explanation in this PR would be spot on)?

2021-07-13 06:47 UTC, WixoLeo commented
@Lawouach can you validate if I wrote the changelog section correctly? I assume that the version will be created once merged right?

2021-07-13 08:20 UTC, Lawouach requested changes
LGTM. Just a few minor changes.

2021-07-13 08:20 UTC, Lawouach commented on CHANGELOG.md
> +
Do not set the version and date in a PR. I'll change them after the merge before the next release.

2021-07-13 08:20 UTC, Lawouach commented on CHANGELOG.md
> +  Therefore the experiment continues to run. [#210][ctk210]
Indent this under the `Remove the problematic log line from exit.py` so that it looks like a single entry.

2021-07-13 08:20 UTC, Lawouach commented on CHANGELOG.md
> +[1.19.1]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.19.0...1.19.1
Not needed as per above.

2021-07-13 08:39 UTC, WixoLeo commented on CHANGELOG.md
> +
Done

2021-07-13 08:39 UTC, WixoLeo commented on CHANGELOG.md
> +  Therefore the experiment continues to run. [#210][ctk210]
Done

2021-07-13 08:39 UTC, WixoLeo commented on CHANGELOG.md
> +[1.19.1]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.19.0...1.19.1
Done

2021-07-13 08:51 UTC, Lawouach commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.19.1...HEAD
Sorry to bother you, but you don't want to change the version in this one either. I'll do that at release time :)

2021-07-13 08:51 UTC, Lawouach requested changes
almost there :)

2021-07-13 09:56 UTC, WixoLeo commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.19.1...HEAD
No worries, never used changelog before so it was bound to get a lot of comments haha.
Fixed

2021-07-13 12:01 UTC, Lawouach commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.19.1...HEAD
Just checking if you have pushed a change removing this modification?.

2021-07-13 14:06 UTC, WixoLeo commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.19.1...HEAD
Pfff silly me, pushed it now, sorry

2021-07-14 08:07 UTC, WixoLeo commented
> almost there :)

Is there anything else I can do?

2021-07-15 12:12 UTC, Lawouach commented
Sorry for being so slow Leo. One last thing, just edit your commit message to add your name/email as a signature (as per our DCO):

```
My  message body...


Signed-off-by: Your Name <my@email.com>

```

thanks

2021-07-15 14:00 UTC, WixoLeo commented
> Sorry for being so slow Leo. One last thing, just edit your commit message to add your name/email as a signature (as per our DCO):
> 
> ```
> My  message body...
> 
> 
> Signed-off-by: Your Name <my@email.com>
> ```
> 
> thanks

@Lawouach Done :)

2021-07-15 14:05 UTC, merged