Resolves #210
chaostoolkit/chaostoolkit-lib pull request #234
Opened 2021-09-01 18:45 UTC by Tam-Lin

The tests are taking advantage in some places of os.environ being a global namespace.  They check to make sure that KUBE_API_URL is set to "http://1.2.3.4", but they don't actually explicitly set it.  Plus, os.environ is a system call, so it really should be mocked, not set in the testcase itself.

Signed-off-by: Kevin McKenzie <kmckenzi@us.ibm.com>

2021-09-02 08:25 UTC, ciaranevans requested changes

2021-09-02 08:25 UTC, ciaranevans commented on tests/test_secret.py
> +=======
Hey @Tam-Lin I'm guessing all the git annotations aren't meant to be around? 😄

2021-09-02 17:36 UTC, Tam-Lin commented
<sigh>Not sure how those ended up there.  I removed the git annotations and repushed.

2021-09-02 17:36 UTC, Tam-Lin commented on tests/test_secret.py
> +=======
Not sure how those ended up there. I removed the git annotations and repushed.

2021-09-08 08:10 UTC, ciaranevans commented
@Tam-Lin Going to close this one as you make another PR which is now in.

2021-09-08 08:10 UTC, closed without merging