New dry flag
chaostoolkit/chaostoolkit-lib pull request #241
Opened 2021-09-13 15:22 UTC by roeiK-wix

Hey, we finished refactoring the dry flag according to what we agreed on.
Flag options:
--dry=actions - Not executing any actions in the method and rollback sections.
--dry=probes - Not executing any probes in the method and rollback sections.
--dry=activities - Not executing any actions and probes in the method and rollback sections. (the same as the old dry flag)
--dry=pause - Not executing any pause.
During the implementation, we found that the old and now the new dry flag are just working inside the method section.
But in all the other sections such as the steady-state and in the controls, the activities are still working as normal (meaning no dry)
We wanted to know if this is the logic you meant to when you thought about adding a dry flag?
Also, we found that the probes aren't returning any value, (as expected to a function that doesn't been called) so it always returns None and so it's always false tolerance.

In this new implementation, we kept the old logic and added the new logic with actionless, probeless, and pauseless.

Also, review this PR -> chaostoolkit/chaostoolkit#220

We didn't add any tests for this new logic because we wanted you to first review this PR and then we will add the tests.
Thanks.
@Lawouach

2021-09-14 12:18 UTC, Lawouach commented
Could we avoid merge commits and prefer rebvasing instead?

2021-09-14 12:32 UTC, Lawouach commented
> During the implementation, we found that the old and now the new dry flag are just working inside the method section.

Can you clarify this? I think the dry flag is applicable to the ssh, right?

2021-09-14 12:36 UTC, Lawouach requested changes
Sorry, I had to stop the review as there was quite a lot of changes that didn't seem to ber part of the PR but came from old commit? is that expected?

2021-09-14 12:36 UTC, Lawouach commented on chaoslib/activity.py
> +                d=pause_before))
why come back to the old .format ?

2021-09-14 13:02 UTC, roeiK-wix commented
> Could we avoid merge commits and prefer rebasing instead?

Yes, in the next contribution we will be much more careful, we won't merge, only rebase.

2021-09-14 13:08 UTC, roeiK-wix commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.21.0...HEAD
This is probably because of some merges that I took from the master.
I did cherry-pick only my commits but still, some of them are got in.

2021-09-14 15:12 UTC, Lawouach requested changes
more feedback

2021-09-14 15:12 UTC, Lawouach commented on CHANGELOG.md
> -
Not sure this was meant to be removed.

2021-09-14 15:12 UTC, Lawouach commented on CHANGELOG.md
> +-   Initial release
any change here?

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/activity.py
> +from chaoslib.types import Activity, Configuration, Experiment, Run, Secrets, Dry
order alphabetically

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/activity.py
> +        * `"type"` the kind of activity, one of `"python"`, `"process"` or `"http"`
why is this changed?

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/activity.py
> +    dry: Dry,
Probably should be:

```
dry: Dry = None
```

This means the calls do not expect the flag to be set by default.

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/activity.py
> +                logger.debug(f" => succeeded with '{result}'")
why removing this space?

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/activity.py
> +            logger.error(f" => failed: {error_msg}")
likewise

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/experiment.py
> +    Dry
I guess this should also be ordered

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/run.py
> -
why remove this?

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/run.py
> +        dry: Dry = experiment.get("dry", None)
not opposed to the typing annotation here but is this necessary? we support Python 3.6 whioch introduced them on variables but I find it nice to casually support older 3.x if we can. 

So is there a specific use case?

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/run.py
> +
remove the blank lines between the conditions

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/run.py
> +
logger.warning should be logger.warning here. Perhaps a better phrase like:

```
Running experiment with dry `actions|pobes|everything`

2021-09-14 15:12 UTC, Lawouach commented on chaoslib/types.py
> +    def from_string(value: str) -> 'Dry':
As you can return `None`, you should make the return type `Optional['Dry']`

2021-09-15 06:41 UTC, roeiK-wix commented
> > During the implementation, we found that the old and now the new dry flag are just working inside the method section.
> 
> Can you clarify this? I think the dry flag is applicable to the ssh, right?

So, I checked again, and the dry flag is working in all of the stages (include in the ssh) but it doesn't work in the controls.
So, if I have a probe in the control it will be executed.

2021-09-15 09:12 UTC, CharlieMoon37 commented on chaoslib/hypothesis.py
> +from chaoslib.types import Configuration, Experiment, Secrets, Tolerance, Dry
Make sure this is ordered alphabetically as well

2021-09-15 09:15 UTC, CharlieMoon37 commented on chaoslib/activity.py
> +# -*- coding: utf-8 -*-
Since `pyupgrade --py36-plus` was run across the project, there isn't a need to include an `utf-8`encoding with every python file as this in now the default with python 3.6+

2021-09-15 09:56 UTC, roeiK-wix commented on chaoslib/run.py
> +        dry: Dry = experiment.get("dry", None)
I think in this case it's helpful for the foreign eye that knows this is a Dry-type and not a string.

2021-09-15 11:27 UTC, Lawouach commented on chaoslib/run.py
> +        dry: Dry = experiment.get("dry", None)
But it isn't, the data in the experiment *is* a string.

2021-09-15 12:20 UTC, roeiK-wix commented on chaoslib/run.py
> +        dry: Dry = experiment.get("dry", None)
I populate the experiment with the Dry enum, so later I can use it in the activities function as an enum and not as a string.

2021-09-15 12:21 UTC, roeiK-wix commented on chaoslib/run.py
> +        dry: Dry = experiment.get("dry", None)
Tell me if its ok by you.

2021-09-15 13:03 UTC, CharlieMoon37 commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.21.0...HEAD
The beginning of the `CHANGELOG.md` should look like this ...

```
# Changelog

## [Unreleased][]

[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.21.0...HEAD

### Changed

* Switched from pycodestyle/pylama to `black`, `flake8`, `isort`
* Update CI builds to build, lint, and test
* Allow nesting of secrets
* Secrets loaded from a vault can be overridden by variables
* In secrets testcases, change the os.environ to be a patch, not an assignment within the testcase.
* Add `.github/workflows/close_stale_issues.yaml` to mark issues as `Stale`
after 365 days of inactivity and to close them after 7 days of being marked
`Stale`.
* Run `pyupgrade --py36-plus` across whole project
* Updated `.github/workflows/release.yaml` to check that both `CHANGELOG.md`
and `chaoslib/__init__.py` get updated in line with a new version
* Updated `Makefile` to specify `python3` instead of `python`

### Added

* Added `.github/workflows/check_pr.yaml` which checks if a PR has modified the
CHANGELOG.md and if it changed/added tests
* Added dry run options:
  * `--dry=activities` runs all activities as dry run. (same as the old flag)
  * `--dry=actions` runs all actions as dry run.
  * `--dry=probes` runs all probes as dry run.
  * `--dry=pause` runs all activities with no pausing.

## [1.21.0][] - 2021-08-23

             ...
```

2021-09-15 13:13 UTC, CharlieMoon37 commented
At the moment, the **Build, Test, and Lint / lint (pull_request)** check is continually failing
To resolve this, you can make use of the `Makefile` by following the [Develop](https://github.com/chaostoolkit/chaostoolkit-lib#develop) and [Formatting and Linting](https://github.com/chaostoolkit/chaostoolkit-lib#formatting-and-linting) steps in the chaostoolkit-lib `README.md` before committing any new changes

2021-09-19 13:37 UTC, roeiK-wix commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.21.0...HEAD
But this is ctk-lib changelog not ctk.
@CharlieMoon37

2021-09-19 13:49 UTC, CharlieMoon37 commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.21.0...HEAD
What are you suggesting?

2021-09-19 13:58 UTC, roeiK-wix commented
> At the moment, the **Build, Test, and Lint / lint (pull_request)** check is continually failing
> To resolve this, you can make use of the `Makefile` by following the [Develop](https://github.com/chaostoolkit/chaostoolkit-lib#develop) and [Formatting and Linting](https://github.com/chaostoolkit/chaostoolkit-lib#formatting-and-linting) steps in the chaostoolkit-lib `README.md` before committing any new changes

Done, please approve @CharlieMoon37

2021-09-19 14:09 UTC, CharlieMoon37 commented
Hi @roeiK-wix,
It's looking like we are very nearly there ...
I hope the changes that we have suggested make sense to you and that you understand where we were coming from. At the moment, I cannot approve the PR as @Lawouach still has some requested changes that have not been resolved. I think we will have to wait until tomorrow when they are back online so they can have a look and either re-request changes or decided that they have been resolved. At the moment though, I am unable to approve - but from my perspective, things are looking good :)
Sorry to hold you back

(I'll have a look at the PR for the chaostoolkit now)

2021-09-19 14:15 UTC, roeiK-wix commented
> Hi @roeiK-wix,
> It's looking like we are very nearly there ...
> I hope the changes that we have suggested make sense to you and that you understand where we were coming from. At the moment, I cannot approve the PR as @Lawouach still has some requested changes that have not been resolved. I think we will have to wait until tomorrow when they are back online so they can have a look and either re-request changes or decided that they have been resolved. At the moment though, I am unable to approve - but from my perspective, things are looking good :)
> Sorry to hold you back
> 
> (I'll have a look at the PR for the chaostoolkit now)

I understand completely what you asked, this is what code quality looks like.
I didn't bother by doing those changes that you asked me to.
I hope that in the future ill know how to contribute with fewer mistakes :)
tanks for your comments it helped me to fix the problems quicker.

2021-09-30 07:31 UTC, Lawouach approved these changes

2021-09-30 07:31 UTC, merged