Add dynamic config logic
chaostoolkit/chaostoolkit-lib pull request #247
Opened 2021-11-08 16:46 UTC by roeiK-wix

2021-11-10 08:34 UTC, Lawouach requested changes
Starting the discussion. I would also appreciate some tests please.

2021-11-10 08:34 UTC, Lawouach commented on CHANGELOG.md
> +## [1.24.0][] - 2021-11-08
Do not set the version on PR :)

2021-11-10 08:34 UTC, Lawouach commented on CHANGELOG.md
> +[Unreleased]: https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.24.0...HEAD
likewise

2021-11-10 08:34 UTC, Lawouach commented on CHANGELOG.md
> +  and then the return value of this probe will be the config you wish to set.
This should be below the [Unreleased] on line 17

2021-11-10 08:34 UTC, Lawouach commented on chaoslib/configuration.py
> +    The secrets argument it's in case we need the secrets inside the config_probe.
Could you rephrase this. I don't find it quite clear enough.

2021-11-10 08:34 UTC, Lawouach commented on chaoslib/configuration.py
> +    }
Set this between backticks please.

2021-11-10 08:34 UTC, Lawouach commented on chaoslib/run.py
> +        self.config = load_dynamic_configuration(self.config, self.secrets)
Why is this a different call? Can't we call this from `load_configuration` itself?

2021-11-10 08:34 UTC, Lawouach commented
Please rebase this branch from head of master and push again.

2021-11-10 11:33 UTC, roeiK-wix commented on chaoslib/run.py
> +        self.config = load_dynamic_configuration(self.config, self.secrets)
The reason I created another function is because I had to pass to the function the secrets of the experiment, but the problem is that it's being created only after.
(Initially, I created this functionality inside the load_config function).

2021-11-10 11:49 UTC, roeiK-wix commented on chaoslib/run.py
> +        self.config = load_dynamic_configuration(self.config, self.secrets)
And another reason that it's after the regular load_config function is to get all the env vars after they are set in the load_config.

2021-11-25 13:41 UTC, Lawouach requested changes
Sorry for the delay.

A few more comments.

2021-11-25 13:41 UTC, Lawouach commented on chaoslib/configuration.py
> +from chaoslib.activity import run_activity
Would you mind trying to do that import from within the function and run `black` (our linter) again? The reason is that, with that import we bring a lot of other things inside a light module (configuration.py). Postponing the import may avoid that pity until needed.

2021-11-25 13:41 UTC, Lawouach commented on chaoslib/configuration.py
> +
can you explain why this is added?

2021-11-25 13:41 UTC, Lawouach commented on chaoslib/configuration.py
> +    config: Dict[str, Any], secrets: Dict[str, Dict[str, str]]
we have types `Configuration` and `Secrets` for these

2021-11-25 13:41 UTC, Lawouach commented on chaoslib/configuration.py
> +            if value["type"] == "probe":
These two lines could be squashed into one:

```
if isinstance(value, dict) and value.get("type") == "probe":
```

2021-11-25 13:41 UTC, Lawouach commented on chaoslib/configuration.py
> +                value["provider"]["secrets"] = secrets
why?

2021-12-01 15:55 UTC, roeiK-wix commented on chaoslib/configuration.py
> +
So if let says, I have two configurations, one with type env and the other with type probe (the dynamic config), the dynamic config will not appear and the `conf[key]` and so not appear in the self.config, and later on im passing the self.config to the load_dynamic_config.

2021-12-15 13:32 UTC, Lawouach approved these changes
LGTM

2021-12-15 13:32 UTC, merged