fix(hypothesis): clear up error message when expect fails
chaostoolkit/chaostoolkit-lib pull request #269
Opened 2023-09-21 08:57 UTC by mattiascockburn

If the `expect` string includes strings that should be replaced the debug/error message should include the final `expect` string where all placeholders are substituted. Otherwise the user is lead to believe that the substitution itself failed.

2023-09-22 15:32 UTC, mattiascockburn commented
@Lawouach do you think this is a good idea or should i rework this?

2023-09-22 15:54 UTC, Lawouach commented
@mattiascockburn I think it makes a lot of sense

2023-09-22 15:55 UTC, Lawouach requested changes
Can you add a changelog entry please?

2023-09-22 15:56 UTC, Lawouach commented
It seems that breaks at least one test. That's good :)

2023-09-25 12:15 UTC, mattiascockburn commented
@Lawouach hopefully i fixed it up enough :-)

2023-09-28 08:16 UTC, Lawouach commented
Hey @mattiascockburn sorry for being a tad slow on this one. I cannot see the changelog entry in any of the commits though.

2023-09-28 09:36 UTC, Lawouach approved these changes
LGTM

2023-09-28 09:42 UTC, merged